apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-in-the-house.com/app: simple2
  name: simple2
  namespace: k8s-in-the-house
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 12345
    name: http
  selector:
    k8s-in-the-house.com/app: simple2
