apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-go-instrumentation
  namespace: k8s-in-the-house
spec:
  exporter:
    endpoint: http://jaeger-collector.jaeger:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
