apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-instrumentation
  namespace: k8s-in-the-house 
spec:
  exporter:
    endpoint: "http://jaeger-collector.jaeger.svc.cluster.local:4317"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
