apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-in-the-house.com/app: simple1
  name: simple1
  namespace: k8s-in-the-house
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-in-the-house.com/app: simple1
  template:
    metadata:
      labels:
        k8s-in-the-house.com/app: simple1
      annotations:
        instrumentation.opentelemetry.io/inject-go: go-instrumentation
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/simple1"
    spec:
      containers:
      - image: ghcr.io/drumato/k8s-in-the-house:simple1-latest
        imagePullPolicy: Always
        name: simple1
        ports:
        - name: http
          containerPort: 1323
          protocol: TCP
