apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-in-the-house.com/app: simple1
  name: simple1
  namespace: k8s-in-the-house
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    k8s-in-the-house.com/app: simple1
