repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm
- name: open-telemetry
  url: https://open-telemetry.github.io/opentelemetry-helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: argo-cd
  namespace: argo-cd
  chart: argo/argo-cd
  version: 5.35.0
  values:
  - values/argo.values.yaml
- name: opentelemetry-operator
  namespace: opentelemetry
  chart: open-telemetry/opentelemetry-operator
  version: 0.41.0
  values:
  - values/opentelemetry-operator.values.yaml
- name: kube-prometheus-stack
  namespace: monitoring
  chart: prometheus-community/kube-prometheus-stack
  version: 67.5.0
  values:
  - values/kube-prometheus-stack.values.yaml
