on:
  push:
    branches:
      - main

name: Image Build and Push

jobs:
  publish_docker_image:
    defaults:
      run:
        working-directory: apps/simple1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/pnovel:latest \
          --tag ghcr.io/$GITHUB_ACTOR/pnovel:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/k8s-in-the-house:simple1-latest
          docker push ghcr.io/$GITHUB_ACTOR/k8s-in-the-house:simple1-$(echo $GITHUB_SHA | head -c7)
